In [ ]:

print("DATASET 1")
# opening the file
file1 = open("ucldataset.csv","r")
# making empty list, dict and tup to store data
teams = []
groups = []
nations= {}
played = ()
won = ()
goals = ()
cups = []
# converting tuples to lists for performing operations
plist = list(played)
wlist = list(won)
glist = list(goals)
# extracting data from csv file
while True:
data = file1.readline()
if not data:
break
#print(data)
# storing the data in the data structures
temp = data.split(",")
teams.append(temp[1])
groups.append(temp[2])
nations.update({temp[1]:temp[3]})
plist.append(int(temp[4]))
wlist.append(int(temp[5]))
glist.append(int(temp[6]))
cups.append(int(temp[7]))
file1.close()
# converting lists back to tuples
played = tuple(plist)
won = tuple(wlist)
goals = tuple(glist)
#printing the data
print("Teams = ",teams)
print("\nGroups = ",groups)
print("\nNations = ",nations)
print("\nPlayed = ",played)
print("\nWon = ",won)
print("\nGoals = ",goals)
print("\nCups = ",cups)

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14,19])
c = a*b;
print(c)

ValueError: ignored

In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
b = np.array([2,4,6,8])
print("\nprinting array a:")
print(a)
print("\nprinting array b:")
print(b)
print("\nAdding arrays a and b:")
c = a + b;
print(c)
a) [[3, 6, 9, 12], [4, 8, 11, 14], [12, 24, 45, 11]]
b) [[1, 2, 3, 4], [2, 4, 5, 6], [10, 20, 39, 3]]
c) [[3, 6, 9, 12], [2, 4, 5, 6], [10, 20, 39, 3]]
d) Error


printing array a:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b:
[2 4 6 8]

Adding arrays a and b:
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
c = a * b
print(c)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[1],
                 [2],
                 [3]])

result = arr1 + arr2

print(result)

ValueError: ignored

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1], [2]])

result = arr1 + arr2

print(result.shape)

(2, 3)


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([5, 6])

result = arr1 + arr2

print(result)

[[ 6  8]
 [ 8 10]]


In [ ]:
import numpy as np

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([4, 5, 6])

result = arr1 * arr2

print(result)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
import numpy as np
a = np.array([[2, 3],
              [5, 9]])
a = a + 5
print(a)

[[ 7  8]
 [10 14]]


In [ ]:
x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
y = np.array([1, 10, 100]).reshape(3, 1)
print(y)
print(x + y)


[[  1]
 [ 10]
 [100]]
[[  1   2   3]
 [ 13  14  15]
 [106 107 108]]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3]])
b = np.array([[4], [5], [6]])
a_transposed = np.transpose(a)
b_transposed = np.transpose(b)
result = a_transposed + b_transposed
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
import numpy as np
arr = np.array([[4,2,0,5],[1,3,5,7]])
print (arr.size)

8


In [ ]:

import numpy as np
arr1 = np.array([7,8,9,10])
arr2 = np.array([1,2,3,4])
arr3 = arr1 + arr2
arr3 = arr3*arr1
print (arr3[2])

108


In [ ]:
x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
y = np.array([1, 10, 100]).reshape(3, 1)
print(x + y)

[[  1   2   3]
 [ 13  14  15]
 [106 107 108]]


In [ ]:
# 1.	How can I check if there are any null values in the dataset  using the df.isnull() function?
# 2. null values from the dataset  using the df.dropna() function?
# 3.	How can I remove columns with any null values from the  dataset using the df.dropna(axis=1) function?
# 4.	How can I fill null values in the dataset with a specific value  using the df.fillna(value) function?
# 5.	How can I fill null values in the dataset with the mean value of  the respective column using the df.fillna(df.mean()) function?

# 01) number of students with math score > 80 res1 = df[df['math score']>80]
print("1) Number of students with math 80+  score:",len(res1),'\n',res1.to_string(),'\n\n')

# 02) number of female students who completed test  preparation course
res2 = df[(df['gender']=='female') &	(df['test  preparation course']=='completed')]
print("2) Number of females students who completed prep  course: ",len(res2),'\n',res2.to_string(),'\n\n')

# 03) number students from group A with reading score  greater than 80
res3 = df[(df['race/ethnicity'] == 'group B') &  (df['reading score']>80)]
print('3) Number of group A students with 80+ reading  score:',len(res3),'\n',res3.to_string(),'\n\n')

# 04) Filtering dataset to include only students with  parental level of education = bachelor's or master's res4 = df[(df['parental level of education'] ==
"bachelor's degree") | (df['parental level of education']
== "master's degree")] print(res4.to_string(),'\n\n')

# 05) number of students who have more than 70 in all 3  subjects
res5 = df[ (df['math score'] > 70) & (df['reading score']> 70) & (df['writing score'] > 70) ]
print("5) Number of students with a score of 70 in all 3  subjects:",len(res5),'\n',res5.to_string(),'\n\n')

# 06) Number of female candidates with a score less than  90 in writing
res6 = df[(df['gender'] == 'female') & (df['writing  score'] < 90)]
print("6) Number of female candidates with a score less  than 90 in  writing:",len(res6),'\n',res6.to_string(),'\n\n')

# 07) Number of male candidates in group B
res7 = df[(df['gender'] == 'male') & (df['race/ ethnicity'] == 'group B')]
print("7) Number of male candidates in group  B:",len(res7),'\n',res7.to_string(),'\n\n')

# 08) Number of candidates in group C
res8 = df[df['race/ethnicity'] == 'group C'] print("8) Number of candidates in group  C:",len(res8),'\n',res8.to_string(),'\n\n')

# 09) Number of students with a score greater than 75 in  mathematics
res9 = df[df['math score'] > 75]
print("9) Number of students with a score greater than 75 in mathematics:",len(res9),'\n',res9.to_string(),'\n\n')

# 10) Number of female students who completed the test  preparation course
res10 = df[(df['gender'] == 'female') & (df['test  preparation course'] == 'completed')]
print("10) Number of female students who completed the  test preparation  course:",len(res10),'\n',res10.to_string(),'\n\n')



# 11) Number of male students who completed the test  preparation course

res11 = df[(df['gender'] == 'male') & (df['test  preparation course'] == 'completed')]
print("11) Number of male students who completed the test preparation  course:",len(res11),'\n',res11.to_string(),'\n\n')

# 12) Number of students with a score greater than 60 in  reading
res12 = df[df['reading score'] > 60]
print("12) Number of students with a score greater than  60 in reading:",len(res12),'\n',res12.to_string(),'\n\n')

# 13) Number of female students with a score greater than 60 in writing
res13 = df[(df['gender'] == 'female') & (df['writing  score'] > 60)]
print("13) Number of female students with a score greater than 60 in  writing:",len(res13),'\n',res13.to_string(),'\n\n')

# 14) Number of male students with a score less than 60  in reading
res14 = df[(df['gender'] == 'male') & (df['reading  score'] < 60)]
print("14) Number of male students with a score less than 60 in reading:",len(res14),'\n',res14.to_string(),'\n\n')

# 15) Number of candidates having an associate’s degree  as parental level of education
res15 = df[df['parental level of education'] ==  "associate's degree"]
print("15) Number of candidates having an associate’s  degree as parental level of  education:",len(res15),'\n',res15.to_string(),'\n\n')


SyntaxError: ignored